#!/usr/bin/env python3
"""Generate C source with embedded template files as byte arrays.

Usage: embed_template.py <template_dir> <output_c>

Reads all files from template_dir (respecting filter exclusions),
converts them to static const unsigned char[] arrays, and writes
a C source file with a lookup registry.
"""

import os
import sys


BINARY_EXT = frozenset({'.svg', '.png', '.jpg', '.gif', '.ico', '.woff2'})
EXCLUDE_DIRS = frozenset({'node_modules', 'build', 'public'})
EXCLUDE_FILES = frozenset({'.DS_Store'})


def sanitize_name(path):
    """Convert a relative file path to a valid C identifier."""
    result = []
    for ch in path:
        if ch.isalnum():
            result.append(ch)
        else:
            result.append('_')
    return ''.join(result)


def collect_files(template_dir):
    """Walk template_dir and return sorted list of (rel_path, abs_path, is_binary)."""
    files = []
    for root, dirs, filenames in os.walk(template_dir):
        dirs[:] = sorted(d for d in dirs if d not in EXCLUDE_DIRS)
        for fname in sorted(filenames):
            if fname in EXCLUDE_FILES:
                continue
            abs_path = os.path.join(root, fname)
            rel_path = os.path.relpath(abs_path, template_dir)
            _, ext = os.path.splitext(fname)
            is_binary = ext.lower() in BINARY_EXT
            files.append((rel_path, abs_path, is_binary))
    files.sort(key=lambda x: x[0])
    return files


def write_byte_array(f, var_name, data):
    """Write a static const unsigned char array to file."""
    f.write(f'static const unsigned char {var_name}[] = {{\n')
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_vals = ', '.join(f'0x{b:02x}' for b in chunk)
        f.write(f'  {hex_vals},\n')
    f.write('};\n\n')


def main():
    if len(sys.argv) != 3:
        print(f'usage: {sys.argv[0]} <template_dir> <output_c>', file=sys.stderr)
        sys.exit(1)

    template_dir = sys.argv[1]
    output_c = sys.argv[2]

    files = collect_files(template_dir)
    if not files:
        print(f'error: no files found in {template_dir}', file=sys.stderr)
        sys.exit(1)

    # Pre-read all file data
    file_data = []
    for rel_path, abs_path, is_binary in files:
        with open(abs_path, 'rb') as src:
            data = src.read()
        file_data.append((rel_path, data, is_binary))

    total_bytes = sum(len(d) for _, d, _ in file_data)

    with open(output_c, 'w') as f:
        f.write('/* Generated by scripts/embed_template.py -- DO NOT EDIT */\n\n')
        f.write('#include "phosphor/embedded.h"\n')
        f.write('#include <stddef.h>\n')
        f.write('#include <string.h>\n\n')

        # Write byte arrays
        for rel_path, data, is_binary in file_data:
            var_name = 'embed_' + sanitize_name(rel_path)
            f.write(f'/* {rel_path} ({len(data)} bytes) */\n')
            write_byte_array(f, var_name, data)

        # Write file table
        f.write('static const ph_embedded_file_t embedded_files[] = {\n')
        for rel_path, data, is_binary in file_data:
            var_name = 'embed_' + sanitize_name(rel_path)
            binary_str = 'true' if is_binary else 'false'
            f.write(f'  {{"{rel_path}", {var_name}, {len(data)}, {binary_str}}},\n')
        f.write('};\n\n')

        f.write(f'static const size_t embedded_file_count = {len(file_data)};\n\n')

        # Lookup functions
        f.write('const ph_embedded_file_t *ph_embedded_lookup(const char *path) {\n')
        f.write('  if (!path) return NULL;\n')
        f.write('  for (size_t i = 0; i < embedded_file_count; i++) {\n')
        f.write('    if (strcmp(embedded_files[i].path, path) == 0)\n')
        f.write('      return &embedded_files[i];\n')
        f.write('  }\n')
        f.write('  return NULL;\n')
        f.write('}\n\n')

        f.write('size_t ph_embedded_count(void) {\n')
        f.write('  return embedded_file_count;\n')
        f.write('}\n\n')

        f.write('const ph_embedded_file_t *ph_embedded_list(void) {\n')
        f.write('  return embedded_files;\n')
        f.write('}\n')

    print(f'embedded {len(file_data)} files ({total_bytes} bytes) -> {output_c}',
          file=sys.stderr)


if __name__ == '__main__':
    main()
